import os

# Конфигурация
SUPABASE_URL = "https://wtycmnktsegvpduiylfq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0eWNtbmt0c2VndnBkdWl5bGZxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzgyOTQ4MCwiZXhwIjoyMDYzNDA1NDgwfQ.rGchuGjDLxWyh-44TmZ81gf6QWxute_Du0WD7p-JllY"
SECRET_KEY = os.getenv("SECRET_KEY", "your-secret-key-change-in-production")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
TEACHER_PASSWORD_HASH = os.getenv("TEACHER_PASSWORD_HASH", "$2b$12$9X6vY7jQjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8Q")
STUDENT_PASSWORD_HASH = os.getenv("STUDENT_PASSWORD_HASH", "$2b$12$9X6vY7jQjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8Q")
