import os

# Конфигурация
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
SECRET_KEY = os.getenv("SECRET_KEY", "your-secret-key-change-in-production")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
TEACHER_PASSWORD_HASH = os.getenv("TEACHER_PASSWORD_HASH", "$2b$12$9X6vY7jQjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8Q")
STUDENT_PASSWORD_HASH = os.getenv("STUDENT_PASSWORD_HASH", "$2b$12$9X6vY7jQjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8QjQJ8Q")
